apiVersion: v1
kind: Service
metadata:
  name: trend-app
spec:
  type: LoadBalancer
  selector:
    app: trend    # ← Match this to deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
